name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [8.1, 8.2]

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug
      - name: Composer install
        run: composer install
      - name: Lint
        run: composer lint
      - name: Static Analysis
        run: composer stan
      - name: Make directory
        run: mkdir -p build/logs
      - name: Test
        run: vendor/bin/phpunit tests/ --coverage-clover build/logs/clover.xml
